### PR TITLE
Add find_by_email to Customer

### LINKED ISSUE #106: Add find_by_email Method to Customer
Add a find_by_email method to Customer like Account has

### PR DESCRIPTION
**Pull request by remear**
Customer has no means to find a Customer by email address. A Balanced customer requested this ability.

Resolves #106

### CODE REVIEW

**Comment by rpearce** [comment]
<-- this guy

**Comment by mjallday** [comment]
Customers do not have a unique constraint on `email_address`. What's the behavior if >1 email addresses exist?

**Comment by remear** [comment]
Presently it returns one Customer. I'm not sure on the ordering.

**Comment by mjallday** [comment]
Can we document that then so at least it's known behavior? Otherwise +1

**Comment by remear** [comment]
Added a note to the method comment.

**Comment by mjallday** [comment]
I had my finger on the merge button and then looked at [the spec](https://github.com/balanced/balanced-api/blob/master/resources/customers.rst#request). It appears we should be filtering by `email` not `email_address` as the param.

https://github.com/balanced/balanced-ruby/pull/107/files#L0R32

While `email_address` will work currently, it will be deprecated in the next revision of the API.

**Comment by rpearce** [comment]
I've had my eye on this commit. Very nice catch

**Comment by remear** [comment]
I'll have a new commit for that shortly.

**Comment by remear** [comment]
Updated

**Pull request merged**
